name: Deploy Application

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: deploy to ASG
      run: |
        echo "Pushing to ASG"
        instance_ids=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name hodhod --query 'AutoScalingGroups[].Instances[].InstanceId' --output text)
        echo $instance_ids
        echo ${{ secrets.PEM_FILE }} > PEM_FILE && chmod 600 PEM_FILE
        cat PEM_FILE
        
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }} 

