name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Package repository
      id: package
      run: |
        
        touch app_$(date +"%Y-%m-%d").tar.gz
        ls
        tar --exclude=app_$(date +"%Y-%m-%d").tar.gz app_$(date +"%Y-%m-%d").tar.gz .
        echo "::set-output name=package_path::app_$(date +"%Y-%m-%d").tar.gz"
        
    - name: Upload to S3
      run: |
        echo "Uploading to S3"
        aws s3 cp ${{ steps.package.outputs.package_path }} s3://${{ secrets.S3_BUCKET_NAME}} 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }} 
