name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Package repository
      id: package
      run: |
        tar -czf app_$(date +"%Y-%m-%d").tar.gz .
        echo "::set-output name=package_path::app_$(date +"%Y-%m-%d").tar.gz"
      
    - name: Upload to S3
      id: upload
      needs: package
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
        SOURCE_DIR: ${{ steps.package.outputs.package_path }}
      env:
        AWS_S3_BUCKET: yourname_app
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: your-region



